### ISSUE TITLE
Crash on Load

### ISSUE THREAD

**Issue by MentalMonk** [cem3cem3/CostCalculatorIssues#1]
Created a Folder, put the .dll into the folder, server crashes on load. Find attached the log file.
[log_210427054145.log](https://github.com/cem3cem3/CostCalculatorIssues/files/6383587/log_210427054145.log)

**Comment by cem3cem3** [comment]
I haven't implemented a bit-ness check on this mod yet so this is a legitimate issue, but its probably a bit-ness related issue. For anyone coming to this issue with the same problem, please fill out this form so I know how I should fix it: https://forms.gle/un9CKVSJbiS4y4fh6

**Comment by cem3cem3** [comment]
Should be resolved with new version.
