### ISSUE TITLE
Exception was thrown: ln1, col 5882016

### ISSUE THREAD

**Issue by StoneLegion** [cem3cem3/CostCalculatorIssues#12]
![image](https://user-images.githubusercontent.com/425853/150292438-c5d76aad-191f-4c0f-b44f-ed91acc8d9e5.png)

Just testing the mod for the first time. Threw it in and rebooted it and got that error. No other mods touching the eco web server.

**Comment by StoneLegion** [comment]
I noticed on the Mod Page you suggested using F12
![image](https://user-images.githubusercontent.com/425853/150407868-8f2b8ea3-3428-423d-983c-74383d98a756.png)

**Comment by cem3cem3** [comment]
Should be fixed in the new version.
