### ISSUE TITLE
[2.7.0.9.5] Harmony version mismatch with Nid's Chat Tags

### ISSUE THREAD

**Issue by Dave247** [cem3cem3/CostCalculatorIssues#15]
Just a heads up, running cost calculator 2.7.0.9.5 with Nid's Toolbox, specifically the [chat tags module](https://forum.play.eco/filebase/file/288-nidtoolbox-chat-tags-module) will trigger a warning due to both mods making use of two different Harmony library versions. Thankfully the server seems smart enough to know what to do with it, and I don't expect it to lead to any issues with either mod, but just wanted to mention it. I believe that looking at the server start-up logs it will loads mods in alphabetical order, which means that CostCalculator will almost always be one of the first mods to load. 

```
[16:42:15.971] [1] [ Warn] [Eco] An assembly with the same name but lower version has already been loaded. 
	Given assembly: 0Harmony, Version=2.2.1.0 from: Eco.Nid.ChatTags
	Loaded assembly: 0Harmony, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null
```

**Comment by cem3cem3** [comment]
Fixed in 2.8.0.9.5.1R.
