### ISSUE TITLE
Labor Calculation Issue

### ISSUE THREAD

**Issue by HoeenCoder** [cem3cem3/CostCalculatorIssues#16]
Hello. I'm unsure if this is a bug or a personal misunderstanding of how labor is calculated into prices, but this doesn't seem right so I thought I'd ask. I am calculating the price of nails made from Iron Ore using a Stamp Mill, Screening Machine, Blast Furnace, and Anvil. I have included labor costs (Level 7 Mining, Level 7 Smelting) at a price of 0.01 currency per calorie. The input price for iron ore is 0.25 currency each. The price of a single nail using the `value/value` node shows as 1.32 currency, which doesn't seem correct at all:

![image](https://user-images.githubusercontent.com/11671268/169627633-674f0eab-ae6a-4c7f-bad2-b7b43b46ed11.png)

If I choose to use an `item/ingredient` node for Iron Bars at the calculated price for them after smelting (1.57 currency) instead of connecting the output of the Iron Bar recipe, the price for nails drops dramatically to 0.30 currency.

![image](https://user-images.githubusercontent.com/11671268/169627590-d1eabfea-46e5-4d36-9917-06e9bc5e5995.png)

What appears to be going on is that Cost Calculator is not taking labor into account properly. It seems to just be adding the full labor cost on top of the price for each individual nail, which is excessive considering 16 are made, not 1 from each iteration of the project.

For example with the upgrades and costs included in this diagram, 16 nails can be made from 0.5 iron bars (1.57 / 2 = 0.79 rounded up). Meaning the base price for a nail should be 0.05 currency (rounded up). Adding labor costs of 0.25 / 16 or 0.01 or 0.02 gives a final cost of 0.06-0.07 currency per nail. This may vary a bit depending on how things are exactly calculated, but this is my understanding of how costs should be calculated (`value/value` nodes should give me the "break even" price if I don't add anything to them).

Please let me know if I am misunderstanding anything, and thanks for your help in advance!

**Comment by cem3cem3** [comment]
You're correct. I don't think the calories are adjusted for the output counts of items right now. I'll get it fixed for the next version, thanks for the report!

**Comment by cem3cem3** [comment]
Should be fixed in 2.9.0.9.5.2R
