### ISSUE TITLE
Cannot Import JSON from the same server 

### ISSUE THREAD

**Issue by Nicktentjr** [cem3cem3/CostCalculatorIssues#17]
When trying to import a calculator with an export from the same server, it gives the following error:
The graph you are trying to load is from a newer version of the CostCalculator: v 2.7

Current version:
v2.7.0.9.5.0R

Changing the JSON to earlier versions (2.6, etc) does not fix this.

Example JSON:
`{
	"version": "2.7",
	"nodeGraph":
	{
		"nodes":
		[
			{
				"type": "costCalculator.craft",
				"position":
				{
					"posX": 603,
					"posY": 137
				},
				"titleColor":
				{
					"red": 255,
					"green": 255,
					"blue": 255,
					"alpha": 255,
					"ansiColor": 7
				},
				"titleBackgroundColor":
				{
					"red": 101,
					"green": 162,
					"blue": 57,
					"alpha": 255,
					"ansiColor": 0
				},
				"bodyBackgroundColor":
				{
					"red": 247,
					"green": 247,
					"blue": 247,
					"alpha": 255,
					"ansiColor": 0
				},
				"title": "Crafting Recipe",
				"collapsed": false,
				"id": 27,
				"lastTable": "Eco.Mods.TechTree.TailoringTableObject",
				"craft": "Cloth"
			},
			{
				"type": "costCalculator.table",
				"position":
				{
					"posX": 181,
					"posY": 231
				},
				"titleColor":
				{
					"red": 255,
					"green": 255,
					"blue": 255,
					"alpha": 255,
					"ansiColor": 7
				},
				"titleBackgroundColor":
				{
					"red": 101,
					"green": 162,
					"blue": 57,
					"alpha": 255,
					"ansiColor": 0
				},
				"bodyBackgroundColor":
				{
					"red": 247,
					"green": 247,
					"blue": 247,
					"alpha": 255,
					"ansiColor": 0
				},
				"title": "Crafting Table",
				"collapsed": false,
				"id": 28,
				"table": "Eco.Mods.TechTree.TailoringTableObject",
				"currency": "",
				"minuteFee": 0,
				"craftFee": 0
			},
			{
				"type": "costCalculator.module",
				"position":
				{
					"posX": -184,
					"posY": 244
				},
				"titleColor":
				{
					"red": 255,
					"green": 255,
					"blue": 255,
					"alpha": 255,
					"ansiColor": 7
				},
				"titleBackgroundColor":
				{
					"red": 101,
					"green": 162,
					"blue": 57,
					"alpha": 255,
					"ansiColor": 0
				},
				"bodyBackgroundColor":
				{
					"red": 247,
					"green": 247,
					"blue": 247,
					"alpha": 255,
					"ansiColor": 0
				},
				"title": "Upgrade Module",
				"collapsed": false,
				"id": 29,
				"module": "Eco.Mods.TechTree.TailoringUpgradeItem"
			},
			{
				"type": "costCalculator.player",
				"position":
				{
					"posX": -61,
					"posY": 100
				},
				"titleColor":
				{
					"red": 255,
					"green": 255,
					"blue": 255,
					"alpha": 255,
					"ansiColor": 7
				},
				"titleBackgroundColor":
				{
					"red": 101,
					"green": 162,
					"blue": 57,
					"alpha": 255,
					"ansiColor": 0
				},
				"bodyBackgroundColor":
				{
					"red": 247,
					"green": 247,
					"blue": 247,
					"alpha": 255,
					"ansiColor": 0
				},
				"title": "Player",
				"collapsed": false,
				"id": 5,
				"player": "Zaliron"
			},
			{
				"type": "costCalculator.labor",
				"position":
				{
					"posX": 240,
					"posY": 68
				},
				"titleColor":
				{
					"red": 255,
					"green": 255,
					"blue": 255,
					"alpha": 255,
					"ansiColor": 7
				},
				"titleBackgroundColor":
				{
					"red": 101,
					"green": 162,
					"blue": 57,
					"alpha": 255,
					"ansiColor": 0
				},
				"bodyBackgroundColor":
				{
					"red": 247,
					"green": 247,
					"blue": 247,
					"alpha": 255,
					"ansiColor": 0
				},
				"title": "Labor",
				"collapsed": false,
				"id": 6,
				"currency": "Hamburgers",
				"value": 0.1
			},
			{
				"type": "costCalculator.value",
				"position":
				{
					"posX": 1016,
					"posY": 105
				},
				"titleColor":
				{
					"red": 255,
					"green": 255,
					"blue": 255,
					"alpha": 255,
					"ansiColor": 7
				},
				"titleBackgroundColor":
				{
					"red": 101,
					"green": 162,
					"blue": 57,
					"alpha": 255,
					"ansiColor": 0
				},
				"bodyBackgroundColor":
				{
					"red": 247,
					"green": 247,
					"blue": 247,
					"alpha": 255,
					"ansiColor": 0
				},
				"title": "Value",
				"collapsed": false,
				"id": 24
			}
		],
		"links":
		[
			[
				27,
				0,
				24,
				0
			],
			[
				28,
				0,
				27,
				0
			],
			[
				6,
				0,
				27,
				1
			],
			[
				29,
				0,
				28,
				0
			],
			[
				5,
				0,
				6,
				0
			]
		]
	}
}`

**Comment by cem3cem3** [comment]
v2.7.0.9.5.0R is not the most recent version of the Cost Calculator. v2.8.0.9.5.1R fixes this issue.
