### ISSUE TITLE
Does not appear to work with 9.3.4 release

### ISSUE THREAD

**Issue by evanah64** [cem3cem3/CostCalculatorIssues#2]
Installed new this morning by placing the file into the mods directory of our existing server. Launch the browser and only the default Scientific Data, Elected Officials, etc. tabs are showing. Does it need an update or did we possibly miss a step?

Cross posted on the eco mods community discord

**Comment by cem3cem3** [comment]
Try to open your web-interface in incognito. It's probably a cache issue. I've heard someone say they had to open it in incognito too after they installed it on the white-tiger server.

**Comment by evanah64** [comment]
That did it, thank you for your time!
