### ISSUE TITLE
Value Multiplier

### ISSUE THREAD

**Issue by johnclark96** [cem3cem3/CostCalculatorIssues#6]
Maybe add a node similar to Addition to Multiply say a value like if you're marking up the cost of something you can do say
Value of a Hewn Log is 5 Dollars and you want to mark it up by x 1.5 and sell it for 7.5 so you don't have to constantly use a calculator.

**Comment by cem3cem3** [comment]
Something like this has been on my mind for a while now and I do intend to add it after the current full re-write is done and released. It will be much, much easier for me to implement new nodes once the re-write is done.

**Comment by ruohki** [comment]
second on this. Something that lets you multiply to add a little profit margin ontop

**Comment by cem3cem3** [comment]
Being able to do multiplications on a given currency is now functionally possible with the new math nodes. However these do not currently function on currency values directly and need to be converted from values to plain numbers and back.
I'll be closing the issue as there now exists a better workaround than a literal external calculator though.
